# @package _global_

run_name: sd15-inversion-lora-r16-lr5e-5-cosine-fp16
checkpoint_dir: /net/pr2/projects/plgrid/plggzzsn2026/plgatarsander/checkpoints/sd15_inversion_lora_r16_lr5e-5_cosine_fp16

max_train_steps: 171225
learning_rate: 5e-5
weight_decay: 0.0
gradient_accumulation_steps: 4
gradient_checkpointing: true
max_grad_norm: 1.0
save_training_state: true

resume:
  enabled: false
  mode: adapter
  checkpoint_path: null
  global_step: null

lr_scheduler:
  name: cosine
  warmup_steps: 1000
  num_cycles: 1
  power: 1.0

log_every_steps: 50
eval_every_steps: 1000
save_every_steps: 5000
max_val_batches: 128

wandb:
  project: diff-inversion
  mode: online

validation_preview:
  enabled: false

model:
  torch_dtype: float16
  variant: fp16

data:
  root_dir: /net/pr2/projects/plgrid/plggzzsn2026/plgatarsander/data/processed/sd15_trajectories_stacked/train
  val_root_dir: /net/pr2/projects/plgrid/plggzzsn2026/plgatarsander/data/processed/sd15_trajectories_stacked/val
  latents_file_name: trajectory.pt
  conditioning_file_name: conditioning.pt
  targets_dir_name: targets
  target_eps_file_name: target_eps.pt
  require_training_cache: true
  batch_size: 2
  num_workers: 4
  pin_memory: true

lora:
  r: 16
  lora_alpha: 8
  init_lora_weights: true
  target_modules:
    - to_q
    - to_k
    - to_v
    - to_out.0
  lora_dropout: 0.0
