# @package _global_

defaults:
  - sd15_lora
  - _self_

run_name: sd15-inversion-lora-r16-lr5e-6-cosine-bf16
checkpoint_dir: /net/pr2/projects/plgrid/plggdiffusion/plgatarsander/checkpoints/sd15_inversion_lora_r16_lr5e-6_cosine_bf16

learning_rate: 5e-6
