# @package _global_

run_name: sdxl-inversion-lora-r32-lr5e-5-cosine-bf16
checkpoint_dir: /net/tscratch/people/plgatarsander/ZZSN_data/checkpoints/sdxl_inversion_lora_r32_lr5e-5_cosine_bf16

max_train_steps: 171225
learning_rate: 5e-5
weight_decay: 0.0
gradient_accumulation_steps: 4
gradient_checkpointing: true
max_grad_norm: 1.0
save_training_state: true

resume:
  enabled: false
  mode: adapter
  checkpoint_path: null
  global_step: null

lr_scheduler:
  name: cosine
  warmup_steps: 1000
  num_cycles: 1
  power: 1.0

log_every_steps: 50
eval_every_steps: 1000
save_every_steps: 5000
max_val_batches: 128

training_target:
  mode: conditional
  guidance_scale: ${model.guidance_scale}
  branch_loss_weight: 0.0
  cfg_loss_weight: 0.0
  cfg_temb_conditioning:
    embedding_type: mlp
    hidden_dim: 128
    log_mean: 1.51749664
    log_std: 0.53920626
    fourier_num_bands: 32
    fourier_max_frequency: 16.0

wandb:
  project: diff-inversion
  mode: online

data:
  root_dir: /net/tscratch/people/plgatarsander/ZZSN_data/processed/sdxl_trajectories_stacked/train
  val_root_dir: /net/tscratch/people/plgatarsander/ZZSN_data/processed/sdxl_trajectories_stacked/val
  latents_file_name: trajectory.pt
  conditioning_file_name: conditioning.pt
  targets_dir_name: targets
  target_eps_file_name: target_eps.pt
  target_uncond_eps_file_name: target_eps_uncond.pt
  require_training_cache: true
  batch_size: 2
  num_workers: 4
  pin_memory: true

model:
  torch_dtype: bfloat16
  variant: fp16

lora:
  r: 32
  lora_alpha: 16
  init_lora_weights: true
  target_modules:
    - to_q
    - to_k
    - to_v
    - to_out.0
    - ff.net.0.proj
    - ff.net.2
  lora_dropout: 0.0
