defaults:
  - sample_gather
  - override /hydra/launcher: plgrid_submitit_slurm
  - _self_

job_id: 0
job_specs:
  - start_index: 0
    num_samples: 3425
  - start_index: 3425
    num_samples: 3425
  - start_index: 6850
    num_samples: 3425
  - start_index: 10275
    num_samples: 3425
  - start_index: 13700
    num_samples: 3424
  - start_index: 17124
    num_samples: 3424
  - start_index: 20548
    num_samples: 3424
  - start_index: 23972
    num_samples: 3424
