defaults:
  - sample_gather_sd15
  - override /hydra/launcher: plgrid_submitit_slurm
  - _self_

data:
  prompts_jsonl: /net/tscratch/people/plgatarsander/ZZSN_data/processed/recap_coco/train.jsonl

output_dir: /net/pr2/projects/plgrid/plggdiffusion/plgatarsander/data/processed/sd15_trajectories_stacked/train

job_id: 0
job_specs:
  - start_index: 0
    num_samples: 3425
  - start_index: 3425
    num_samples: 3425
  - start_index: 6850
    num_samples: 3425
  - start_index: 10275
    num_samples: 3425
  - start_index: 13700
    num_samples: 3425
  - start_index: 17125
    num_samples: 3425
  - start_index: 20550
    num_samples: 3425
  - start_index: 23975
    num_samples: 3421
