# @package _global_

input_dir: data/processed/sdxl_trajectories
overwrite: false
save_inversion_latents: true
save_inversion_pred_noises: true

lora:
  enabled: false
  mode: single
  checkpoint_path: null
  scale: 1.0
  cfg_temb_conditioning:
    embedding_type: mlp
    hidden_dim: 128
    log_mean: 1.51749664
    log_std: 0.53920626
    fourier_num_bands: 32
    fourier_max_frequency: 16.0
  active_steps: null
  active_fraction: null
  r: 16
  lora_alpha: 8
  lora_dropout: 0.0
  bias: none
  init_lora_weights: gaussian
  target_modules:
    - to_k
    - to_q
    - to_v
    - to_out.0
    - ff.net.0.proj
    - ff.net.2
