# @package _global_

repo_dir: /net/people/plgrid/plgatarsander/Diffusion-Inversion-for-Image-Editing
data_path: /net/pr2/projects/plgrid/plggdiffusion/plgatarsander/data/raw/PIE-Bench_v1
output_path: ${repo_dir}/masactrl_lora_eval_outputs

edit_category_list:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
edit_method_list:
  - lora+masactrl
rerun_exist_images: false

lora:
  checkpoint_path: /net/pr2/projects/plgrid/plggdiffusion/plgatarsander/checkpoints/sd15_inversion_lora_r16_lr5e-5_cosine_bf16/checkpoint_step_130000.pt
  r: 16
  lora_alpha: 8
  lora_dropout: 0.0
  scale: 1.0
